//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ayubaweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUser
    {
        public int AUId { get; set; }
        public string Username { get; set; }
        public string Passwords { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
