//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ayubaweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Legend
    {
        public int LegendId { get; set; }
        public string Symbol { get; set; }
        public string Descriptions { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
