//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ayubaweb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_a7ad46_qnEntities1 : DbContext
    {
        public db_a7ad46_qnEntities1()
            : base("name=db_a7ad46_qnEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminUser> AdminUsers { get; set; }
        public virtual DbSet<EmailConfirmation> EmailConfirmations { get; set; }
        public virtual DbSet<Legend> Legends { get; set; }
        public virtual DbSet<QuestionTitle> QuestionTitles { get; set; }
        public virtual DbSet<ResponseQuestion> ResponseQuestions { get; set; }
        public virtual DbSet<SampleOrganization> SampleOrganizations { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<Vw_ResponseQuestion> Vw_ResponseQuestion { get; set; }
    }
}
