//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ayubaweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_ResponseQuestion
    {
        public int RId { get; set; }
        public int UserId { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        public string JobTitle { get; set; }
        public string CurrentAddressOrganization { get; set; }
        public string AreaSpecialization { get; set; }
        public decimal WorkingExperience { get; set; }
        public string Question1 { get; set; }
        public string Answer1 { get; set; }
        public string Question2 { get; set; }
        public string Answer2 { get; set; }
        public string DateRegister { get; set; }
        public Nullable<int> Active { get; set; }
        public string Qtype { get; set; }
        public string Qtitle { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public string DateAnswer { get; set; }
    }
}
